language: ruby

jdk:
  - oraclejdk8

rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - ruby-head

gemfile:
  - Gemfile

script: bundle exec rake spec SPEC_OPTS="-fd"

matrix:
  allow_failures:
    - rvm: ruby-head

sudo: false

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
