language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.2.0
  - ruby-head

gemfile:
  - Gemfile

script: bundle exec rake spec

matrix:
  allow_failures:
    - rvm: ruby-head

sudo: false

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
