language: ruby

jdk:
  - oraclejdk8

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head

gemfile:
  - Gemfile

script: bundle exec rake spec SPEC_OPTS="-fd"

matrix:
  allow_failures:
    - rvm: ruby-head

sudo: false

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
