---
version: "{build}"
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - bundle --version
  - bundle install
build_script:
  - bundle exec rake build
test_script:
  # - bundle exec rake spec
  - bundle exec rspec -fd spec/td/command/workflow_spec.rb -e'installs java + digdag and can run a workflow'
environment:
  matrix:
    - ruby_version: "22"
    - ruby_version: "22-x64"
